apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: awsome-media-frontend-deployment
  labels:
    app: awsome-media-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awsome-media-frontend
  template:
    metadata:
      labels:
        app: awsome-media-frontend
    spec:
      containers:
      - name: tf-test-dev
        image: icp.ghama.io:8500/ns-admin1/awsome-media-frontend:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits: 
            memory: "512Mi" 
            cpu: "2" 