apiVersion: v1
kind: Service
metadata:
  name: awsome-media-frontend-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: awsome-media-frontend
  type: NodePort 